import type { JobListing } from '@/types/job';

export const seedJobs: JobListing[] = [
  {
    id: 'job-1',
    title: 'Maid',
    titleHi: 'मेड / नौकरानी चाहिए',
    occupationTag: 'maid',
    salary: 8000,
    salaryPeriod: 'month',
    location: { area: 'इंदिरा नगर', lat: 26.85, lng: 80.95 },
    employerName: 'शर्मा निवास',
    employerRating: 4.6,
    distanceKm: 1.2,
    postedAt: '2026-07-10T00:00:00.000Z',
  },
  {
    id: 'job-2',
    title: 'Society Guard',
    titleHi: 'सोसाइटी गार्ड चाहिए',
    occupationTag: 'society_guard',
    salary: 400,
    salaryPeriod: 'day',
    location: { area: 'गोमती नगर', lat: 26.86, lng: 81.0 },
    employerName: 'ग्रीन वैली अपार्टमेंट्स',
    employerRating: 4.2,
    distanceKm: 2.8,
    postedAt: '2026-07-11T00:00:00.000Z',
  },
  {
    id: 'job-3',
    title: 'Driver',
    titleHi: 'कार ड्राइवर चाहिए',
    occupationTag: 'driver',
    salary: 15000,
    salaryPeriod: 'month',
    location: { area: 'हजरतगंज', lat: 26.85, lng: 80.94 },
    employerName: 'कपूर परिवार',
    employerRating: 4.8,
    distanceKm: 3.5,
    postedAt: '2026-07-09T00:00:00.000Z',
  },
  {
    id: 'job-4',
    title: 'Electrician',
    titleHi: 'इलेक्ट्रिशियन चाहिए',
    occupationTag: 'electrician',
    salary: 600,
    salaryPeriod: 'day',
    location: { area: 'आलमबाग', lat: 26.8, lng: 80.9 },
    employerName: 'सिटी मॉल',
    employerRating: 4.0,
    distanceKm: 5.1,
    postedAt: '2026-07-08T00:00:00.000Z',
  },
  {
    id: 'job-5',
    title: 'Delivery',
    titleHi: 'डिलीवरी पार्टनर चाहिए',
    occupationTag: 'delivery',
    salary: 500,
    salaryPeriod: 'day',
    location: { area: 'चारबाग', lat: 26.83, lng: 80.92 },
    employerName: 'क्विकमार्ट लॉजिस्टिक्स',
    employerRating: 3.9,
    distanceKm: 4.3,
    postedAt: '2026-07-12T00:00:00.000Z',
  },
  {
    id: 'job-6',
    title: 'Cook',
    titleHi: 'रसोइया चाहिए',
    occupationTag: 'cook',
    salary: 10000,
    salaryPeriod: 'month',
    location: { area: 'महानगर', lat: 26.87, lng: 80.93 },
    employerName: 'वर्मा परिवार',
    employerRating: 4.5,
    distanceKm: 2.0,
    postedAt: '2026-07-07T00:00:00.000Z',
  },
];
