import type { GovtScheme } from '@/types/scheme';

export const seedSchemes: GovtScheme[] = [
  {
    id: 'ayushman-bharat',
    name: 'Ayushman Bharat (PM-JAY)',
    nameHi: 'आयुष्मान भारत (PM-JAY)',
    description: '₹5 लाख तक का मुफ़्त इलाज हर साल, पूरे परिवार के लिए।',
    category: 'स्वास्थ्य',
    iconKey: 'heart',
    eligibility: {
      minAge: null,
      maxAge: null,
      gender: 'any',
      occupationTags: [],
      incomeCeiling: 15000,
      migrationRequired: null,
    },
    documentsRequired: ['aadhaar'],
    applyUrl: 'https://pmjay.gov.in',
    howToSteps: [
      'नज़दीकी CSC केंद्र या अस्पताल जाएँ',
      'आधार कार्ड दिखाएँ',
      'राशन/आय प्रमाण जमा करें',
      'पात्रता जाँच के बाद कार्ड बनेगा',
    ],
  },
  {
    id: 'pm-sym',
    name: 'PM Shram Yogi Maandhan (PM-SYM)',
    nameHi: 'PM श्रम योगी मानधन (PM-SYM)',
    description: '60 साल के बाद हर महीने ₹3,000 पेंशन।',
    category: 'पेंशन',
    iconKey: 'shield',
    eligibility: {
      minAge: 18,
      maxAge: 40,
      gender: 'any',
      occupationTags: [],
      incomeCeiling: 15000,
      migrationRequired: null,
    },
    documentsRequired: ['aadhaar'],
    applyUrl: 'https://maandhan.in',
    howToSteps: [
      'आधार व बैंक पासबुक लेकर CSC जाएँ',
      'मासिक अंशदान चुनें (₹55–₹200)',
      'फॉर्म भरकर मोबाइल नंबर दें',
      'PM-SYM कार्ड प्राप्त करें',
    ],
  },
  {
    id: 'e-shram',
    name: 'e-Shram Card',
    nameHi: 'ई-श्रम कार्ड',
    description: 'असंगठित क्षेत्र के मज़दूरों का राष्ट्रीय रजिस्ट्रेशन कार्ड।',
    category: 'रजिस्ट्रेशन',
    iconKey: 'file-text',
    eligibility: {
      minAge: 16,
      maxAge: 59,
      gender: 'any',
      occupationTags: [],
      incomeCeiling: null,
      migrationRequired: null,
    },
    documentsRequired: ['aadhaar'],
    applyUrl: 'https://eshram.gov.in',
    howToSteps: [
      'eshram.gov.in पर जाएँ या CSC सेंटर जाएँ',
      'आधार से जुड़ा मोबाइल नंबर डालें',
      'OTP से सत्यापन करें',
      'e-Shram कार्ड डाउनलोड करें',
    ],
  },
  {
    id: 'pmkvy',
    name: 'Skill India / PMKVY',
    nameHi: 'स्किल इंडिया / PMKVY',
    description: 'मुफ़्त कौशल प्रशिक्षण और प्रमाण पत्र।',
    category: 'प्रशिक्षण',
    iconKey: 'award',
    eligibility: {
      minAge: 15,
      maxAge: 45,
      gender: 'any',
      occupationTags: [],
      incomeCeiling: null,
      migrationRequired: null,
    },
    documentsRequired: ['aadhaar'],
    applyUrl: 'https://pmkvyofficial.org',
    howToSteps: [
      'नज़दीकी प्रशिक्षण केंद्र खोजें',
      'अपना व्यवसाय/कौशल चुनें',
      'आधार से रजिस्टर करें',
      'प्रशिक्षण पूरा कर प्रमाण पत्र पाएँ',
    ],
  },
  {
    id: 'pm-awas',
    name: 'PM Awas Yojana',
    nameHi: 'PM आवास योजना',
    description: 'पक्का घर बनाने के लिए सब्सिडी।',
    category: 'आवास',
    iconKey: 'home',
    eligibility: {
      minAge: null,
      maxAge: null,
      gender: 'any',
      occupationTags: [],
      incomeCeiling: 18000,
      migrationRequired: null,
    },
    documentsRequired: ['aadhaar'],
    applyUrl: 'https://pmaymis.gov.in',
    howToSteps: [
      'pmaymis.gov.in पर आवेदन करें',
      'आधार व आय प्रमाण अपलोड करें',
      'सर्वे टीम घर का निरीक्षण करेगी',
      'मंज़ूरी के बाद किस्त में राशि मिलेगी',
    ],
  },
];
